### ISSUE TITLE
Medical - Known Bugs

### ISSUE THREAD

**Issue by MrEnward** [acemod/ACE-Anvil#31]
Reforger DarkGru Servers
Medical System Specific

Bugs:
A. UPDATED**Carrying system specifically causes mass crashes, removed carrying but mass crashes are still consistent. Carrying prevents players from entering vehicles (victim and/or medic), may cause hurt player to be stuck in uncon position despite being conscious, and can create a visual glitch for other players where the victim is conscious and moving but the player model is still on the ground so they cannot be shot when behind cover.

B. Wounds are nearly impossible to find, or, bandage prompt fails to appear for console players at times, unsure which.

D. Unable to remove unconscious players from some vehicles. Seen in both vanilla and modded vehicles. A specific list will be added. 

E. UPDATED**Hidden bleeds. More common if both legs are bleeding, but bandaging upper body will disable bandaging of 1 leg. (If one leg bleeds, after bandaging any upper body appendage leg bleed icon can disappear but bleed continues and cannot be bandaged. If two legs are bleeding, after bandaging any upper body appendage and 1 of 2 legs, bleed glitch reoccurs).

H. NEW**Applying saline to an arm before a bandaging the bleed will prevent you from bandaging at all. (In the case that it's intentional to prevent bandaging an arm with a saline bag for realism, you still CANT bandage even after saline is gone.)

I. UPDATED**Applying morphine to an unconscious player seems to reset a condition pertaining to unconsciousness so that they remain unconscious for an additional 10 minutes from the time of application. Even after bandaging and saline. The result is an extended period of time before Epinephrine can be administered, which at times also means that they gain consciousness on their own before you have an opportunity to apply epinephrine. (Still testing)

AWESOME MOD SO FAR GUYS! KEEP IT UP!

Edit: Will add more as we bug hunt.
-Getting a copy of the bug log during mass crashes.
4/5/24
-F. Added.
-C. Replaced with G.
4/6/24
-G. Removed.
-A. and E. Updated. F. Removed.
4/7/24
-H. Added. 
4/9/24
I. Added.
4/11/24
I. Updated.
ACE Mods removed from servers due to overwhelming bugs, log flooding, and resource issues. Testing halted for the time being.

**Comment by jonpas** [comment]
G is intentional as we want the same in ACE3. You shouldn't magically be able to tell someone is dead (or at least that's the long term goal).

**Comment by MrEnward** [comment]
> G is intentional as we want the same in ACE3. You shouldn't magically be able to tell someone is dead (or at least that's the long term goal).

Got it! Thank you!

**Comment by Kexanone** [comment]
A - Has been fixed in the meantime
B, E and H - Covered in #58
D - Likely a vanilla issue
I - See https://discord.com/channels/976165959041679380/976165959935099022/1226281827808051310 on how to treat patients.

For future reference: If you got some other bugs to report, please open a new issue for each rather than a single issue.
