### ISSUE TITLE
Medical - Pharmacokinetics and pharmacodynamics

### ISSUE THREAD

**Issue by Kexanone** [acemod/ACE-Anvil#38]
## Background

In the basic medical system, morphine and epinephrine just heal the pain respective resilience hit zones with a constant rate over a fixed time. During their effect duration, you cannot administer another dose.

## Proposal

The idea is to make a new option to replace the behavior described above by a more realistic model, where the drug concentration and effect change over time. Moreover, drugs should no longer heal the hit zones. We introduce instead a drug-adjusted health getter that returns the sum of the hit zone's health and all drug effects. This will turn morphine into a pain suppressor and epinephrine into a resilience enhancer, rather than healer.

#### Proposed Model

Two consecutive first-order reactions:

$$\begin{flalign}
&\ce{P ->[k_a] A ->[k_d] \otimes}&
\end{flalign}$$
- $\ce{P}$: Precursor state
- $\ce{A}$: Active state
- $k_a$: Activation rate constant
- $k_d$: Deactivation rate constant (metabolism)

#### Corresponding Rate Law

$$\begin{flalign}
& \begin{pmatrix}\frac{d\ce{[P]}}{dt} \\\\ \frac{d\ce{[A]}}{dt}\end{pmatrix}  =  \begin{pmatrix}-k_a & 0 \\\\ k_a & - k_d\end{pmatrix}\begin{pmatrix}\ce{[P]} \\\\ \ce{[A]}\end{pmatrix} &
\end{flalign}$$

#### Solution

$$\begin{flalign}
& \begin{pmatrix}\ce{[P]} \\\\ \ce{[A]}\end{pmatrix}(t) = \begin{pmatrix}e^{-k_a t} \\\\ \frac{k_a}{k_a-k_d}\Big(e^{-k_d t}-e^{-k_a t}\Big)\end{pmatrix}\ce{[P]}_0 &
\end{flalign}$$

### Pharmacodynamics

Hill equation:

$$\begin{flalign}
& E(t) = \frac{E_{max}\cdot\ce{[A]}(t)}{\ce{[A]_{EC50}} + \ce{[A]}(t)} &
\end{flalign}$$
- $E$: Effect
- $E_{max}$: Maximum effect
- $\ce{[A]}_{EC50}$: Half-maximum effect concentration

### Config Parameters

- Administered substance concentration ($\ce{[P]}_0$)
- Activation rate constant ($k_a$)
- Deactivation rate constant ($k_d$)
- Maximum effect ($E_{max}$)
- Half-maximum effect concentration ($\ce{[A]_{EC50}}$)

## Additional Notes

- In principle the same model could be used with separate parameters for the Hill equation for simulating OD.
- Guidelines for the medical system should contain recommended dosing intervals to keep a reasonable steady state.
- Drug administration times will have to be logged to be able to dose them properly.

## References

1. Meibohm et al. _Int. J. Impotence Res._ **2007**, _19_, 253–264.

**Comment by bluefieldcreator** [comment]
Pharmacokinetics seems like it would be a first in the industry in general, I dont think any other mod or game has or has aimed to simulate pharmaceutical substances before. 

Looking torwards more updates on this!

**Comment by Kexanone** [comment]
Technically, ACE3 already does simulate drug effects as a function of time, but rather than a linear combination of exponentials it uses a parabola for the increase and then switches to a falling line for the decay and the drug effects have a linear response.
