### ISSUE TITLE
Setting `m_bSecondChanceOnHeadEnabled` to `true` doesn't work.

### ISSUE THREAD

**Issue by Kexanone** [acemod/ACE-Anvil#39]
It seems that the mission header parser cannot handle `true` and `false`. It will both parse to `false`. On the other hand, setting it to `1`, does parse to `true`. As the parsing is likely done by the engine, we cannot fix this on our side, so we'll have to advocate using integers instead in the documentations.

**Comment by jonpas** [comment]
Just like good old Arma config.
