### ISSUE TITLE
Medical - Bandages can sometimes not be applied, even though the patient is still bleeding

### ISSUE THREAD

**Issue by Kexanone** [acemod/ACE-Anvil#58]
See title

**Comment by Kexanone** [comment]
#59 in fact did not completely solve it

**Comment by MichaelJRM** [comment]
Are you 100% sure this is a bug?

Sometimes you need to scroll to see the action to bandage.

**Comment by Kexanone** [comment]
There are plenty of reports and also first-hand experience from our dev team.

**Comment by Kexanone** [comment]
Closed in favor of https://feedback.bistudio.com/T183512
