### ISSUE TITLE
Update crashes server

### ISSUE THREAD

**Issue by 7thSim** [acemod/ACE-Anvil#86]
**Mods (complete and add to the following information):**
- **Arma Reforger:** 1.2.0.76
- **ACE Core:** 1.1.2
- _Other ACE mods for reproducing the issue_

**Description:**
When attempting to start server (Windows) it crashes and displays this error message; 
![Screenshot 2024-07-09 162653](https://github.com/acemod/ACE-Anvil/assets/12490726/e9f663c6-0bd1-4b26-b298-a9bcd8131d3f)

**Steps to reproduce:**
_Follow [this flowchart](https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp)!_

1. Stop server and activate ACE All In One
2. Start Server
3. Get Error message
4. Server crash/destroyed

**Expected behavior:**
My server was working before I stopped and restarted it. 

**Which platform are you on?**
- PC 

**Where did the issue occur?**
- Dedicated 

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server LOG files (`console.log` and (`crash.log`)). An instruction to find your LOG files can be found [here](https://community.bistudio.com/wiki/Arma_Reforger:Crash_Report).

**Additional context:**

**Screenshots:**

**Comment by Kexanone** [comment]
ACE Core wasn't updated yet. Just restart the server again.
